
	SSLEngine on
	SSLCertificateFile	/etc/letsencrypt/live/p2.vbz.ffzg.hr/cert.pem
	SSLCertificateKeyFile	/etc/letsencrypt/live/p2.vbz.ffzg.hr/privkey.pem
	SSLCertificateChainFile	/etc/letsencrypt/live/p2.vbz.ffzg.hr/chain.pem

# don't pass through authorization header!
RequestHeader unset Authorization

# http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#request-bodies
#SetEnv proxy-sendcl 1
#SetEnv proxy-sendchunked 1

# https://httpd.apache.org/docs/2.4/mod/mod_substitute.html
# fix AH01328: Line too long
SubstituteMaxLineLength 10m

# Redirect on-campus users directly to target sites
RewriteEngine On
RewriteCond %{REMOTE_ADDR} ^193\.198\.21[2-5]\.
RewriteCond %{HTTP_HOST} ^(.+)\.p2\.vbz\.ffzg\.hr$
RewriteRule ^/(.*)$ https://%1/$1 [R,L]
